version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db_portfolio
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    expose:
    - 5432

  pgadmin:
    image: "dpage/pgadmin4"
    restart: unless-stopped
    container_name: pgadmin_portfolio
    depends_on:
      - db_portfolio
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuba1095@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_LISTEN_PORT: 8001
    ports: 
      - "5050:8001"
    networks:
      - mynetwork
  web:
    build: .
    command: bash -c "source /code/myenv_linux/bin/activate
     && python /code/portfolio_manager/manage.py makemigrations
      && python portfolio_manager/manage.py migrate
       && python portfolio_manager/manage.py collectstatic --no-input
        && apache2ctl -D FOREGROUND "
    restart: unless-stopped
    container_name: web
    volumes:
      - ./portfolio_manager:/code/portfolio_manager
    ports: 
      - "8000:8000"
      - "80:80"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge