version: '3.7'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db_portfolio
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    expose:
    - 5432
  # This is for our database management   
  pgadmin:
    image: "dpage/pgadmin4"
    restart: unless-stopped
    container_name: pgadmin_portfolio
    depends_on:
      - db_portfolio
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "5050:8001"
    networks:
      - mynetwork
  #web -> activate venv makemigrations migrate collectstatic then run apache2ctl
  web:
    build: .
    command: bash -c "source /code/myenv_linux/bin/activate
     && python /code/portfolio_manager/manage.py makemigrations
      && python portfolio_manager/manage.py migrate
       && python portfolio_manager/manage.py collectstatic --no-input
        && apache2ctl -D FOREGROUND "
    restart: unless-stopped
    container_name: web
    volumes:
      # copy our code to specific place to make changes in time 
      - ./portfolio_manager:/code/portfolio_manager
      # copy our certs https
      - ./generator_lets_encrypt/certbot/etc/letsencrypt/live/jakubk.pl/cert.pem:/etc/letsencrypt/live/jakubk.pl/cert.pem
      - ./generator_lets_encrypt/certbot/etc/letsencrypt/live/jakubk.pl/fullchain.pem:/etc/letsencrypt/live/jakubk.pl/fullchain.pem
      - ./generator_lets_encrypt/certbot/etc/letsencrypt/live/jakubk.pl/privkey.pem:/etc/letsencrypt/live/jakubk.pl/privkey.pem
      - ./http.conf:/etc/apache2/sites-available/http.conf
    
    ports: 
      - "80:80"
      - "443:443"
    # for setting database: name, login, password 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge