version: '3'
services:
  db:
    image: postgres
    # restart: unless-stopped
    container_name: db_portfolio
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    expose:
    - 5432

  pgadmin:
    image: "dpage/pgadmin4"
    # restart: unless-stopped
    container_name: pgadmin_portfolio
    depends_on:
      - db_portfolio
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuba1095@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_LISTEN_PORT: 8001
    ports: 
      - "5050:8001"
    networks:
      - mynetwork
  web:
    build: .
    command: bash -c "python /code/portfolio_manager/manage.py makemigrations && python portfolio_manager/manage.py migrate && python portfolio_manager/manage.py collectstatic --no-input && python portfolio_manager/manage.py runserver 0:8000"
    # restart: unless-stopped
    container_name: web
    volumes:
      - ./portfolio_manager:/code/portfolio_manager
    ports: 
      - "8000:8000"
      - "80:80"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db
    #   - elasticsearch
    networks:
      - mynetwork
  # elasticsearch:
  #   image: launcher.gcr.io/google/elasticsearch2
  #   container_name: elasticsearch
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - mynetwork
# volumes: 
#   postgres-data:
#   esdata:
#     driver: local
networks:
  mynetwork:
    driver: bridge